### ISSUE TITLE
June 2019 Lesson Release checklist

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/socialsci-workshop#31]
If your Maintainer team has decided not to participate in the [June 2019 lesson release](https://carpentries.topicbox.com/groups/maintainers/T61c75ac1a8a89538/timeline-and-process-for-june-lesson-release), please close this issue.

To have this lesson included in the 18 June 2019 release, please confirm that the following items are true:

- [x] Call out boxes (exercises, discussions, tips, etc) render correctly
- [x] Setup instructions are up-to-date, correct, clear, and complete
- [x] File structure is clean (e.g. delete deprecated files, ensure filenames are consistent)
- [x] Some Instructor notes are provided
- [x] Lesson links work as expected

When all checkboxes above are completed, this lesson will be added to the 18 June lesson release. Please leave a comment on carpentries/lesson-infrastructure#26 or contact Erin Becker with questions (ebecker@carpentries.org).

**Comment by ErinBecker** [comment]
I've just noticed that we don't have an official Maintainer for this workshop overview page. Pinging the Maintainers for the other Social Science lessons here to see if anyone would like to act as Maintainer for this repo, which involves making sure that the information on this page stays up to date with curricular changes. @angela-li @juanfung @gtlaflair @chris-prener @PeterSmyth12 @sechilds @gboushey

**Comment by ErinBecker** [comment]
Hey all (@angela-li, @juanfung, @gtlaflair, @chris-prener, @PeterSmyth12, @sechilds, @gboushey) - can anyone confirm whether there are changes that need to be made to this repo in order to keep it up to date with other SocSci lessons that are being released this month?

**Comment by angela-li** [comment]
I can act as a temporary maintainer for now, to check over this repo for the June 2019 Lesson Release! If no one else wants to step up, also happy to step up in the future.

**Comment by angela-li** [comment]
FYI I am editing the checklist to reflect the same one as the Geospatial Workshop Overview (see datacarpentry/geospatial-workshop#41), since not all the lesson checklist items are relevant.

**Comment by angela-li** [comment]
The lesson is ready for the June 2019 release!

**Comment by fmichonneau** [comment]
Thanks for stepping up as a maintainer for this repo!
It's now released! :tada: https://doi.org/10.5281/zenodo.3265744
